### ISSUE TITLE
Lack of documentation around component/datasource/datacolumn etc

### ISSUE THREAD

**Issue by Sharnw** [dandisy/webCore#1]
Hey mate,

I love the package and i've had no problem setting up the dashboard etc.

Just having some trouble getting my head around the component, datasource, datacolumn for creating front-end pages.

Hoping you can add some more detail to the documentation for those features.

Cheers!

**Comment by dandisy** [comment]
Hello @Sharnw,

Have a nice day, and be thankful for your question.

Need to know, for the time being I'm working on developing a better and complete documentation, I'll be happy to let you know when it's ready, so for a quick solution to the issue you're trying you can try webcore-cms ([https://github.com/dandisy/webcore-cms](https://github.com/dandisy/webcore-cms)). Webcore-cms is a webcore already in a complete compilation as web cms, and has implemented components, datasource and datacolumn are integrated.

As a laravel developer I'm sure you'll easily understand what's going on inside the component, datasource and datacolumn by looking at the code and the database that specifies it.

While waiting for the documentation, please try it yourself first.

Greetings friendship,

Cheers!

**Comment by Sharnw** [comment]
That helped me out, thanksa @dandisy 

Was able to get the CMS running with that repo :)
