### ISSUE TITLE
Laravel 5.8

### ISSUE THREAD

**Issue by karneaud** [dandisy/webCore#3]
Would it be compatible with Laravel 5.8?

**Comment by dandisy** [comment]
sorry for the delay, 

yes, webcore is compatible with the latest laravel version, but this (starter) project is built with Laravel version 5.5, you have to change the Laravel version and its dependencies as you want in composer.json

or for simplicity, you can use [webcore-base](https://github.com/dandisy/webcore-base) so you can apply the webcore to existing laravel projects
